name: Automatic Slack Management

on:
  push:
    paths:
      - '**/slack/**/*'
      - 'MAINTAINERS.yaml'
      - 'WORKING_GROUPS.yaml'
      - '.github/workflows/slack-integration.yml'
  
jobs:
  deploy-changes-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false  
      - name: Deploy changes to Slack
        run: |
          cd .github/workflows/slack
          terraform init
          terraform apply \
            -var "slack_token=${{ secrets.SLACK_INFRA_TOKEN }}" \
            -auto-approve